config/routes.rb
Rails.application.routes.draw do
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button{ type: "button", class: "navbar-toggle collapsed", :"data-toggle" => "collapse", :"data-target" => "#bs-example-navbar-collapse-1", :"aria-expanded" => "false" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.navbar-brand{ href: "#" } Wastelands

    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        %li.dropdown
          = link_to users_path, class: "dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do
            Users
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to 'Users list', users_path
            %li{ role: "separator", class: "divider" }
            %li
              = link_to 'Add new user', new_user_path

        %li
          = link_to "#" do
            Link

      %ul.nav.navbar-nav.navbar-right
        %li
          %a{ href: "#" } Current user
        %li
          %a{ href: "#" } Sign out

      %form.navbar-form.navbar-right
        %div.form-group
          %input{ type: "text", class: "form-control", placeholder: "Search" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wasteland</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render "layouts/navbar" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/users/index.haml
%table.table
  %thead
    %th Email
    %th Full name
    %th Birthdate
    %th Admin
    %th
  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.fullname
        %td= user.birthdate
        %td= user.admin
        %td
          = link_to 'Edit', '#'
          |
          = link_to 'Delete', '#'